name: QQQ
on:
  workflow_dispatch:
  schedule:
    - cron: '30 13 * * 1-5'

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install yfinance requests
      - env:
          PUSHDEER_KEY: ${{ secrets.PUSHDEER_KEY }}
        run: python run.py
